#!/usr/bin/env ruby

language = ARGV[0]
filename = ".#{language}.list"

unless File.exists? filename
  puts "No list found for #{language}, try again."
  exit
end

File.read(filename).split.each.with_index do |exercise, index|
  puts "#{index + 1}. #{exercise}"
end
